enum Subjects {
  Maths,
  Chemistry,
  Informatics,
  Arabic,
  French,
  English,
  Biology,
  Geology,
  Sociology,
  Philosophy,
  Physics,
  Astronomy,
  Psychology,
  Spanish,
}

enum Branches {
  Algebra,
  Geometry,
  Statistics,
  Analysis,
  Grammar,
  Conjugation,
  Vocabulary,
  Spelling,
  Expression,
  TextsAnalyse,
  Particles,
  ChemicalReactions,
  NewtonLaws,
  StatesOfTheMaterial,
  Electricity,
  Respiration,
  Digestion,
  Anatomy,
  Energy,
  InternalPhenomenas,
  TheCycleOfRocks,
  TheRocksClassification,
  Algorithmic,
  Programming,
  Hardware,
  Geography,
  History,
  CitizenshipEducation,
  SolarSystem,
  Gravity,
  AstronomicalPhenomenas,
  QuantumMechanic,
}

Map<Subjects, List<Branches>> branches = {
  Subjects.Maths: [
    Branches.Algebra,
    Branches.Geometry,
    Branches.Statistics,
    Branches.Analysis,
  ],
  Subjects.Chemistry: [
    Branches.Particles,
    Branches.ChemicalReactions,
    Branches.QuantumMechanic,
  ],
  Subjects.Physics: [
    Branches.NewtonLaws,
    Branches.StatesOfTheMaterial,
    Branches.Electricity,
    Branches.Energy,
    Branches.Gravity,
  ],
  Subjects.Arabic: [
    Branches.Grammar,
    Branches.Conjugation,
    Branches.Vocabulary,
    Branches.Spelling,
    Branches.Expression,
    Branches.TextsAnalyse,
  ],
  Subjects.French: [
    Branches.Grammar,
    Branches.Conjugation,
    Branches.Vocabulary,
    Branches.Spelling,
    Branches.Expression,
    Branches.TextsAnalyse,
  ],
  Subjects.English: [
    Branches.Grammar,
    Branches.Conjugation,
    Branches.Vocabulary,
    Branches.Spelling,
    Branches.Expression,
    Branches.TextsAnalyse,
  ],
  Subjects.Spanish: [
    Branches.Grammar,
    Branches.Conjugation,
    Branches.Vocabulary,
    Branches.Spelling,
    Branches.Expression,
    Branches.TextsAnalyse,
  ],
  Subjects.Biology: [
    Branches.Respiration,
    Branches.Digestion,
    Branches.Anatomy,
    Branches.Energy,
  ],
  Subjects.Geology: [
    Branches.InternalPhenomenas,
    Branches.TheCycleOfRocks,
    Branches.TheRocksClassification,
  ],
  Subjects.Informatics: [
    Branches.Algorithmic,
    Branches.Programming,
    Branches.Hardware,
  ],
  Subjects.Sociology: [
    Branches.Geography,
    Branches.History,
    Branches.CitizenshipEducation
  ],
  Subjects.Astronomy: [
    Branches.SolarSystem,
    Branches.AstronomicalPhenomenas
  ],
};